services:
  back:
    build:
      dockerfile: src/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - pg
    command: ["python", "main.py"]

  pg:
    image: postgres
    env_file:
      - src/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "POSTGRES_USER", "-p", "POSTGRES_PORT", "-d", "POSTGRES_DB"]
      interval: 5s
      timeout: 3s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - src/.env
    ports:
      - "5050:80"


volumes:
  pgdata: